# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0005_waterlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moisture',
            old_name='hum_value',
            new_name='moi_value',
        ),
        migrations.RenameField(
            model_name='waterlevel',
            old_name='hum_value',
            new_name='water_value',
        ),
    ]
